version: '3'

services:
  app:
    image: node:lts
    tty: true
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "8000:8000"
      - "3001:3001"
      - "8080:8080"
    links:
      - db
    extra_hosts:
      - "github.com:192.30.255.113"
      - "assets-cdn.github.com:151.101.0.133"
      - "avatars2.githubusercontent.com:151.101.64.133"
      - "avatars1.githubusercontent.com:151.101.64.133"
      - "avatars0.githubusercontent.com:151.101.64.133"
      - "collector.githubapp.com:52.73.244.200"
      - "api.github.com:192.30.255.117"
      - "help.github.com:185.199.109.153"
      - "codeload.github.com:192.30.255.120"
      - "gist.github.com:192.30.255.118"
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  mongodata:
